## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  # - "1.0"
  - "1.1"
  - "1.2"
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
git:
  depth: 99999999
codecov: true
# install: mvn install

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi


# uncomment the following lines to override the default test script
script:
  - while sleep 30; do echo "still alive"; done &
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - travis_wait 30 julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("EffectiveWaves")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("EffectiveWaves")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      os: linux
      env:
        - DOCUMENTER_DEBUG=true
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip


# println("documenter_key=", get(ENV, "DOCUMENTER_KEY", ""), "\n",
# "travis_branch=", get(ENV, "TRAVIS_BRANCH", ""), "\n",
# "travis_pull_request=", get(ENV, "TRAVIS_PULL_REQUEST", ""), "\n",
# "travis_repo_slug=", get(ENV, "TRAVIS_REPO_SLUG", ""), "\n",
# "travis_tag=", get(ENV, "TRAVIS_TAG", ""), "\n",
# "travis_event_type=", get(ENV, "TRAVIS_EVENT_TYPE", ""))

# "Deployment criteria:
#     - $(marker(repo_ok)) ENV["TRAVIS_REPO_SLUG"]="$(travis_repo_slug)" occurs in repo="$(repo)"
#     - $(marker(pr_ok)) ENV["TRAVIS_PULL_REQUEST"]="$(travis_pull_request)" is "false"
#     - $(marker(tag_ok)) ENV["TRAVIS_TAG"]="$(travis_tag)" is (i) empty or (ii) a valid VersionNumber
#     - $(marker(branch_ok)) ENV["TRAVIS_BRANCH"]="$(travis_branch)" matches devbranch="$(devbranch)" (if tag is empty)
#     - $(marker(key_ok)) ENV["DOCUMENTER_KEY"] exists
#     - $(marker(type_ok)) ENV["TRAVIS_EVENT_TYPE"]="$(travis_event_type)" is not "cron"
#     Deploying: $(marker(should_deploy))
#     "
