name = "EffectiveWaves"
uuid = "37e8709b-1ed2-53db-b26a-3571262b3cb4"
authors = ["Artur L. Gower <arturgower@gmail.com>"]
version = "0.3.0"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MDBM = "dd61e66b-39ce-57b0-8813-509f78be4b4d"
MultipleScattering = "80a8ab25-5750-5d93-a6d7-4adc97cdd5fb"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ApproxFun = "^0.11, ^0.12"
GSL = "0.6, 0.7"
MDBM = "0.1.4, ^0.2"
MultipleScattering = "^0"
OffsetArrays = "^1"
Optim = "^0"
RecipesBase = "^0, ^1"
Reexport = "^0"
SpecialFunctions = "^0"
StaticArrays = "^0"
julia = "1.1, 1.5"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
